### ISSUE TITLE
if I miss FieldType annotation of the first field of csv, it makes exception 

### ISSUE THREAD

**Issue by smilejinho** [Kazitanvirazad/CSVUtil-JavaBean#4]
Hi~ 
Thanks for your great CSV4POJO library.

I have a problem of my csv reading code.
  
For example,
If I have a csv file with this headers.

id,name,age,address

And I have the pojo class with

public class Employee {
    @FieldType(dataType = Type.STRING, csvColumnName = "name")
    private String name;
    @FieldType(dataType = Type.INTEGER, csvColumnName = "age")
    private Integer age;
    @FieldType(dataType = Type.STRING, csvColumnName = "address")
    private String address;
    ...

}

This code makes below exception.
org.csv4pojoparser.exception.FieldNotMatchedException: CSV header elements does not match with Class fields
at...

**Comment by Kazitanvirazad** [comment]
Employee class must have all the header fields in the same sequence as the header line of the csv file. 
Below is the correct class you can use. I added missing field "id", assuming it as an integer.
```
public class Employee {
      @FieldType(dataType = Type.INTEGER)
      private Integer id;
      @FieldType(dataType = Type.STRING, csvColumnName = "name")
      private String name;
      @FieldType(dataType = Type.INTEGER, csvColumnName = "age")
      private Integer age;
      @FieldType(dataType = Type.STRING, csvColumnName = "address")
      private String address;
}
```

Please try this and let me know if you are facing any trouble using this library.

**Comment by Kazitanvirazad** [comment]
@smilejinho Hope you got the solution above. I am closing this issue. You can create another issue if you are facing any trouble using this library.

**Comment by smilejinho** [comment]
Hi~ 

I thought I can omit some fields in pojo class.
Cause the readme.txt says.
"1. Any field with missing @FieldType annotation will be ignored by CSV4POJO"

So, we can not ignore any csv fields in pojo ?

**Comment by Kazitanvirazad** [comment]
@smilejinho 
Any field with missing @FieldType meaning the field which do not have this annotation will be ignored while reading or writing csv data.
Example:
For csv header: 
id,name,age,address
```
class should have the four annotated fields in sequence.
public class Employee {
      @FieldType(dataType = Type.INTEGER)
      private Integer id;
      @FieldType(dataType = Type.STRING, csvColumnName = "name")
      private String name;
      @FieldType(dataType = Type.INTEGER, csvColumnName = "age")
      private Integer age;
      @FieldType(dataType = Type.STRING, csvColumnName = "address")
      private String address;
}
```
Any field with missing @FieldType meaning:
```
public class Employee {
      @FieldType(dataType = Type.INTEGER)
      private Integer id;
      @FieldType(dataType = Type.STRING, csvColumnName = "name")
      private String name;
      @FieldType(dataType = Type.INTEGER, csvColumnName = "age")
      private Integer age;
      private String company;
      @FieldType(dataType = Type.STRING, csvColumnName = "address")
      private String address;
      private Float salary;
}
```
In the above class  company and salary are not annotated, which means this two fields will be ignored while reading or writing the csv. 
All the csv fields must be mapped in the class with annotation and also the class can have extra fields.

**Comment by smilejinho** [comment]
Ah,, I was misunderstanding.
Thanks you for your detail explanation.
